volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: ~/data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: ~/data/wordpress
      o: bind
      type: none

services:
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    restart: on-failure
  nginx:
    container_name: nginx
    build: requirements/nginx/
    networks:
      - inception
    ports:
      - "443:443"
    restart: on-failure
    depends_on:
      - wordpress
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
     - inception
    ports:
      - "9000:9000"
    restart: on-failure
    depends_on:
      - mariadb
networks:
  inception:
    driver: bridge